const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.bound,
		C3.Behaviors.Tween,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Cnds.IsOnScreen,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{Is_under_utensil: 0},
	{Is_Swapped: 0},
	{Has_crooked_utensil: 0},
	{InitialX: 0},
	{InitialY: 0},
	{Apron_shadow: 0},
	{Wooden_2_shadow: 0},
	{Steel_9_shadow: 0},
	{Steel_7_shadow: 0},
	{Steel_3_shadow: 0},
	{Steel_8_shadow: 0},
	{Steel_4_shadow: 0},
	{Wooden_1_shadow: 0},
	{Cutter_shadow: 0},
	{Steel_5_shadow: 0},
	{Mitton_1_shadow: 0},
	{Steel_1_shadow: 0},
	{Cutboard_shadow: 0},
	{Pan_shadow: 0},
	{Syringe_shadow: 0},
	{Steel_6_shadow: 0},
	{Mitton_2_Shadow: 0},
	{Steel_2_shadow: 0},
	{Batch: 0},
	{On_shadow: 0},
	{Is_placed: 0},
	{Is_straight: 0},
	{StartX: 0},
	{StartY: 0},
	{Apron: 0},
	{Steel_1: 0},
	{Steel_5: 0},
	{Steel_2: 0},
	{Cutboard: 0},
	{Pan: 0},
	{Steel_7: 0},
	{Steel_3: 0},
	{Steel_8: 0},
	{Steel_4: 0},
	{Mitton_1: 0},
	{Cutter: 0},
	{Steel_9: 0},
	{Wooden_2: 0},
	{Steel_6: 0},
	{Syringe: 0},
	{Wooden_1: 0},
	{Mitton_2: 0},
	{Points: 0},
	{Hanger: 0},
	{Timer: 0},
	{BG: 0},
	{Band: 0},
	{For_objective: 0},
	{Anxi_animation: 0},
	{Anxi_animation_alert: 0},
	{Just_alert: 0},
	{PopUp_alert: 0},
	{PopUp_lost: 0},
	{PopUp_time_alert: 0},
	{PopUp_win: 0},
	{Start_game: 0},
	{PopUp_paused: 0},
	{PopUp_after_msg: 0},
	{PopUp_timesup: 0},
	{Txt_5_sec_all: 0},
	{Txt_5_sec_auto: 0},
	{Txt_anxi_crooked: 0},
	{Txt_auto_crooked: 0},
	{Txt_game_over: 0},
	{Txt_just_alert_crooked: 0},
	{Txt_keep_all: 0},
	{Txt_keep_auto: 0},
	{Txt_lost: 0},
	{Txt_win: 0},
	{Txt_wrong_utensil: 0},
	{For_panel: 0},
	{Button_exit: 0},
	{Button_pause: 0},
	{Button_adjust: 0},
	{Button_retry: 0},
	{Button_start: 0},
	{Button_continue: 0},
	{Button_keep_going: 0},
	{Button_reset: 0},
	{Button_finish: 0},
	{Button_replay: 0},
	{Black_fade: 0},
	{Level_time: 0},
	{Initial_Time: 0},
	{Distance_tolerance: 0},
	{Available_utensil: 0},
	{Crooked_angle: 0},
	{Fix_time_cost: 0},
	{Total_batch: 0},
	{Batch_size: 0},
	{Current_batch: 0},
	{Batch_placed: 0},
	{Total_crooked: 0},
	{Total_shadow_swap: 0},
	{Total_utensil_placed: 0},
	{Game_manager: 0},
	{Mouse: 0},
	{Touch: 0},
	{Perfomance_Txt: 0},
	{DragDrop: 0},
	{BoundToLayout: 0},
	{Tween: 0},
	{Utensils: 0},
	{Panels: 0},
	{Shadows: 0},
	{Txt_5_sec: 0},
	{Txt_Crooked: 0},
	{Txt_keep: 0},
	{Game_Paused: 0},
	{WarningX: 0},
	{WarningY: 0},
	{Warning_id: 0},
	{shadow_1_X: 0},
	{shadow_1_Y: 0},
	{shadow_1_id: 0},
	{shadow_2_X: 0},
	{shadow_2_Y: 0},
	{shadow_2_id: 0},
	{shadow_3_X: 0},
	{shadow_3_Y: 0},
	{shadow_3_id: 0},
	{shadow_4_X: 0},
	{shadow_4_Y: 0},
	{shadow_4_id: 0},
	{Candidate_count: 0}
];

self.InstanceType = {
	Apron_shadow: class extends self.ISpriteInstance {},
	Wooden_2_shadow: class extends self.ISpriteInstance {},
	Steel_9_shadow: class extends self.ISpriteInstance {},
	Steel_7_shadow: class extends self.ISpriteInstance {},
	Steel_3_shadow: class extends self.ISpriteInstance {},
	Steel_8_shadow: class extends self.ISpriteInstance {},
	Steel_4_shadow: class extends self.ISpriteInstance {},
	Wooden_1_shadow: class extends self.ISpriteInstance {},
	Cutter_shadow: class extends self.ISpriteInstance {},
	Steel_5_shadow: class extends self.ISpriteInstance {},
	Mitton_1_shadow: class extends self.ISpriteInstance {},
	Steel_1_shadow: class extends self.ISpriteInstance {},
	Cutboard_shadow: class extends self.ISpriteInstance {},
	Pan_shadow: class extends self.ISpriteInstance {},
	Syringe_shadow: class extends self.ISpriteInstance {},
	Steel_6_shadow: class extends self.ISpriteInstance {},
	Mitton_2_Shadow: class extends self.ISpriteInstance {},
	Steel_2_shadow: class extends self.ISpriteInstance {},
	Apron: class extends self.ISpriteInstance {},
	Steel_1: class extends self.ISpriteInstance {},
	Steel_5: class extends self.ISpriteInstance {},
	Steel_2: class extends self.ISpriteInstance {},
	Cutboard: class extends self.ISpriteInstance {},
	Pan: class extends self.ISpriteInstance {},
	Steel_7: class extends self.ISpriteInstance {},
	Steel_3: class extends self.ISpriteInstance {},
	Steel_8: class extends self.ISpriteInstance {},
	Steel_4: class extends self.ISpriteInstance {},
	Mitton_1: class extends self.ISpriteInstance {},
	Cutter: class extends self.ISpriteInstance {},
	Steel_9: class extends self.ISpriteInstance {},
	Wooden_2: class extends self.ISpriteInstance {},
	Steel_6: class extends self.ISpriteInstance {},
	Syringe: class extends self.ISpriteInstance {},
	Wooden_1: class extends self.ISpriteInstance {},
	Mitton_2: class extends self.ISpriteInstance {},
	Points: class extends self.ISpriteInstance {},
	Hanger: class extends self.ISpriteInstance {},
	Timer: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	Band: class extends self.ISpriteInstance {},
	Anxi_animation: class extends self.ISpriteInstance {},
	Anxi_animation_alert: class extends self.ISpriteInstance {},
	Just_alert: class extends self.ISpriteInstance {},
	PopUp_alert: class extends self.ISpriteInstance {},
	PopUp_lost: class extends self.ISpriteInstance {},
	PopUp_time_alert: class extends self.ISpriteInstance {},
	PopUp_win: class extends self.ISpriteInstance {},
	Start_game: class extends self.ISpriteInstance {},
	PopUp_paused: class extends self.ISpriteInstance {},
	PopUp_after_msg: class extends self.ISpriteInstance {},
	PopUp_timesup: class extends self.ISpriteInstance {},
	Txt_5_sec_all: class extends self.ITextInstance {},
	Txt_5_sec_auto: class extends self.ITextInstance {},
	Txt_anxi_crooked: class extends self.ITextInstance {},
	Txt_auto_crooked: class extends self.ITextInstance {},
	Txt_game_over: class extends self.ITextInstance {},
	Txt_just_alert_crooked: class extends self.ITextInstance {},
	Txt_keep_all: class extends self.ITextInstance {},
	Txt_keep_auto: class extends self.ITextInstance {},
	Txt_lost: class extends self.ITextInstance {},
	Txt_win: class extends self.ITextInstance {},
	Txt_wrong_utensil: class extends self.ITextInstance {},
	Button_exit: class extends self.ISpriteInstance {},
	Button_pause: class extends self.ISpriteInstance {},
	Button_adjust: class extends self.ISpriteInstance {},
	Button_retry: class extends self.ISpriteInstance {},
	Button_start: class extends self.ISpriteInstance {},
	Button_continue: class extends self.ISpriteInstance {},
	Button_keep_going: class extends self.ISpriteInstance {},
	Button_reset: class extends self.ISpriteInstance {},
	Button_finish: class extends self.ISpriteInstance {},
	Button_replay: class extends self.ISpriteInstance {},
	Black_fade: class extends self.ITiledBackgroundInstance {},
	Game_manager: class extends self.ISpriteInstance {},
	Level_time: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Perfomance_Txt: class extends self.ITextInstance {},
	Utensils: class extends self.ISpriteInstance {},
	Panels: class extends self.ISpriteInstance {},
	Shadows: class extends self.ISpriteInstance {},
	Txt_5_sec: class extends self.ITextInstance {},
	Txt_Crooked: class extends self.ITextInstance {},
	Txt_keep: class extends self.ITextInstance {}
}