const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Behaviors.DragnDrop,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Text.Cnds.IsOnScreen,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Sprite.Cnds.OnCreated
	];
};
self.C3_JsPropNameTable = [
	{Popup: 0},
	{Button_adjust: 0},
	{Button_continue: 0},
	{Button_finish: 0},
	{Button_keep_going: 0},
	{Button_replay: 0},
	{Button_reset: 0},
	{Button_start: 0},
	{Jar_UID: 0},
	{Is_ignored: 0},
	{Alert_sign: 0},
	{Button_pause: 0},
	{Level_time: 0},
	{Timer_panel: 0},
	{Button_retry: 0},
	{Popup_Pause: 0},
	{Lable_UID: 0},
	{Popup_alert_crooked: 0},
	{Popup_alert_dup_wrin: 0},
	{Popup_final_alert: 0},
	{Popup_keep_going: 0},
	{Popup_Start_Game: 0},
	{Popup_timesup: 0},
	{Popup_win: 0},
	{Popup_time_loss: 0},
	{Popup_out_of_lables: 0},
	{Txt_out_of_labels: 0},
	{Txt_times_up: 0},
	{Txt_last_alert: 0},
	{Txt_5_sec_loss_1: 0},
	{Txt_5_sec_loss_2: 0},
	{Txt_keep_going_1: 0},
	{Txt_keep_going_2: 0},
	{Txt_keep_going_3: 0},
	{Txt_wri_dup_label_1: 0},
	{Txt_wri_dup_label_2: 0},
	{Txt_wri_dup_label_3: 0},
	{Txt_wri_dup_label_4: 0},
	{Txt_crooked_label_1: 0},
	{Txt_crooked_label_2: 0},
	{Txt_crooked_label_3: 0},
	{Txt_win: 0},
	{InitialX: 0},
	{InitialY: 0},
	{PanelX: 0},
	{PanelY: 0},
	{Color: 0},
	{Is_ready: 0},
	{Is_placed: 0},
	{Is_crooked: 0},
	{Is_duplicate: 0},
	{Is_wrinkled: 0},
	{Blue_label_1: 0},
	{Blue_label_2: 0},
	{Blue_label_3: 0},
	{Blue_label_4: 0},
	{Blue_label_5: 0},
	{Blue_label_6: 0},
	{Green_label_1: 0},
	{Green_label_2: 0},
	{Green_label_3: 0},
	{Green_label_4: 0},
	{Green_label_5: 0},
	{Green_label_6: 0},
	{Orange_label_1: 0},
	{Orange_label_2: 0},
	{Orange_label_3: 0},
	{Orange_label_4: 0},
	{Red_label_1: 0},
	{Red_label_2: 0},
	{Red_label_3: 0},
	{Red_label_4: 0},
	{Red_label_5: 0},
	{Yellow_label_1: 0},
	{Yellow_label_2: 0},
	{Yellow_label_3: 0},
	{Yellow_label_4: 0},
	{Yellow_label_5: 0},
	{Yellow_label_1_d: 0},
	{Red_label_1_d: 0},
	{Orange_label_1_d: 0},
	{Green_label_1_d: 0},
	{Blue_label_1_d: 0},
	{Background_level: 0},
	{Background_level_: 0},
	{Tween: 0},
	{Garbage: 0},
	{Has_label: 0},
	{Has_wrinkled: 0},
	{Has_duplicate: 0},
	{Has_crooked: 0},
	{In_Alert: 0},
	{Alert_UID: 0},
	{Jar_blue: 0},
	{Jar_green: 0},
	{Jar_orange: 0},
	{Jar_red: 0},
	{Jar_yellow: 0},
	{Has_sticker: 0},
	{Labels_panel: 0},
	{Black_fade: 0},
	{Audio: 0},
	{Touch: 0},
	{Available_lables: 0},
	{Crooked_angel: 0},
	{Placing_Tolerance: 0},
	{Wrong_labels: 0},
	{Right_lables: 0},
	{Final_alert: 0},
	{Game_Manager: 0},
	{Perfomance_Txt: 0},
	{Jars: 0},
	{Buttons: 0},
	{Popups: 0},
	{DragDrop: 0},
	{Labels: 0},
	{Txts_5_sec_loss: 0},
	{Txts_keep_going: 0},
	{Txts_wri_dup_label: 0},
	{Txts_crooked_label: 0},
	{Game_Is_Paused: 0}
];

self.InstanceType = {
	Button_adjust: class extends self.ISpriteInstance {},
	Button_continue: class extends self.ISpriteInstance {},
	Button_finish: class extends self.ISpriteInstance {},
	Button_keep_going: class extends self.ISpriteInstance {},
	Button_replay: class extends self.ISpriteInstance {},
	Button_reset: class extends self.ISpriteInstance {},
	Button_start: class extends self.ISpriteInstance {},
	Alert_sign: class extends self.ISpriteInstance {},
	Button_pause: class extends self.ISpriteInstance {},
	Level_time: class extends self.ITextInstance {},
	Timer_panel: class extends self.ISpriteInstance {},
	Button_retry: class extends self.ISpriteInstance {},
	Popup_Pause: class extends self.ISpriteInstance {},
	Popup_alert_crooked: class extends self.ISpriteInstance {},
	Popup_alert_dup_wrin: class extends self.ISpriteInstance {},
	Popup_final_alert: class extends self.ISpriteInstance {},
	Popup_keep_going: class extends self.ISpriteInstance {},
	Popup_Start_Game: class extends self.ISpriteInstance {},
	Popup_timesup: class extends self.ISpriteInstance {},
	Popup_win: class extends self.ISpriteInstance {},
	Popup_time_loss: class extends self.ISpriteInstance {},
	Popup_out_of_lables: class extends self.ISpriteInstance {},
	Txt_out_of_labels: class extends self.ITextInstance {},
	Txt_times_up: class extends self.ITextInstance {},
	Txt_last_alert: class extends self.ITextInstance {},
	Txt_5_sec_loss_1: class extends self.ITextInstance {},
	Txt_5_sec_loss_2: class extends self.ITextInstance {},
	Txt_keep_going_1: class extends self.ITextInstance {},
	Txt_keep_going_2: class extends self.ITextInstance {},
	Txt_keep_going_3: class extends self.ITextInstance {},
	Txt_wri_dup_label_1: class extends self.ITextInstance {},
	Txt_wri_dup_label_2: class extends self.ITextInstance {},
	Txt_wri_dup_label_3: class extends self.ITextInstance {},
	Txt_wri_dup_label_4: class extends self.ITextInstance {},
	Txt_crooked_label_1: class extends self.ITextInstance {},
	Txt_crooked_label_2: class extends self.ITextInstance {},
	Txt_crooked_label_3: class extends self.ITextInstance {},
	Txt_win: class extends self.ITextInstance {},
	Blue_label_1: class extends self.ISpriteInstance {},
	Blue_label_2: class extends self.ISpriteInstance {},
	Blue_label_3: class extends self.ISpriteInstance {},
	Blue_label_4: class extends self.ISpriteInstance {},
	Blue_label_5: class extends self.ISpriteInstance {},
	Blue_label_6: class extends self.ISpriteInstance {},
	Green_label_1: class extends self.ISpriteInstance {},
	Green_label_2: class extends self.ISpriteInstance {},
	Green_label_3: class extends self.ISpriteInstance {},
	Green_label_4: class extends self.ISpriteInstance {},
	Green_label_5: class extends self.ISpriteInstance {},
	Green_label_6: class extends self.ISpriteInstance {},
	Orange_label_1: class extends self.ISpriteInstance {},
	Orange_label_2: class extends self.ISpriteInstance {},
	Orange_label_3: class extends self.ISpriteInstance {},
	Orange_label_4: class extends self.ISpriteInstance {},
	Red_label_1: class extends self.ISpriteInstance {},
	Red_label_2: class extends self.ISpriteInstance {},
	Red_label_3: class extends self.ISpriteInstance {},
	Red_label_4: class extends self.ISpriteInstance {},
	Red_label_5: class extends self.ISpriteInstance {},
	Yellow_label_1: class extends self.ISpriteInstance {},
	Yellow_label_2: class extends self.ISpriteInstance {},
	Yellow_label_3: class extends self.ISpriteInstance {},
	Yellow_label_4: class extends self.ISpriteInstance {},
	Yellow_label_5: class extends self.ISpriteInstance {},
	Yellow_label_1_d: class extends self.ISpriteInstance {},
	Red_label_1_d: class extends self.ISpriteInstance {},
	Orange_label_1_d: class extends self.ISpriteInstance {},
	Green_label_1_d: class extends self.ISpriteInstance {},
	Blue_label_1_d: class extends self.ISpriteInstance {},
	Background_level: class extends self.ISpriteInstance {},
	Background_level_: class extends self.ISpriteInstance {},
	Garbage: class extends self.ISpriteInstance {},
	Jar_blue: class extends self.ISpriteInstance {},
	Jar_green: class extends self.ISpriteInstance {},
	Jar_orange: class extends self.ISpriteInstance {},
	Jar_red: class extends self.ISpriteInstance {},
	Jar_yellow: class extends self.ISpriteInstance {},
	Labels_panel: class extends self.ISpriteInstance {},
	Black_fade: class extends self.ITiledBackgroundInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Game_Manager: class extends self.ISpriteInstance {},
	Perfomance_Txt: class extends self.ITextInstance {},
	Jars: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Popups: class extends self.ISpriteInstance {},
	Labels: class extends self.ISpriteInstance {},
	Txts_5_sec_loss: class extends self.ITextInstance {},
	Txts_keep_going: class extends self.ITextInstance {},
	Txts_wri_dup_label: class extends self.ITextInstance {},
	Txts_crooked_label: class extends self.ITextInstance {}
}